services:
  postgres:
    image: postgres:16
    container_name: sistema_gc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tienda_gestion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_gc:/var/lib/postgresql/data

volumes:
  postgres_data_gc:
